### PR TITLE
Made it work on Linux.

### PR DESCRIPTION
**Pull request by JacobHin2**
One issue is now I have no clue about Mac compatibility. It links against libc so there's technically one dependency now.

It just gets the `TIOCGWINSZ` from C because I have no idea how to do it using the standard library (maybe there's a way)

I also had to change the `winsize` struct to use the libc version because it has not yet been written into std.c which would get used under `std.os.system` if you linked libc.

If you agree with the changes could you please check they work?

Thanks

### CODE REVIEW

**Comment by JacobHin2** [comment]
I'll fix the conflicts.

**Comment by JacobHin2** [comment]
OK, I fixed all the conflicts, can you test whether it works for me? Thanks

**Comment by const-void** [comment]
will do!

**Comment by JacobHin2** [comment]
Sorry, I either forgot to do this or it was overwritten at some point.

If it wasn't compiling it should now.

**Pull request merged**
